apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: new-dashboard-configmap
data:
  new-dashboard.json: |-
{{ .Files.Get "dashboards/crawler-dashboards.json" | indent 4}}