apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-crawler.fullname" . }}
  labels:
    {{- include "github-crawler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "github-crawler.selectorLabels" . | nindent 4 }}
